name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.1
      with:
        vs-version: 15.0
    - uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NuGetAPIKey }}
        nuget-version: '5.x'
    - run: nuget restore SyncDevices.sln
      
    - name: MSBuild
      working-directory: patient-monitors
      run: msbuild patient-monitors.sln /p:OutDir="build_output"
    
    - name: Add paho.mqtt.c client library
      run: git clone https://github.com/eclipse/paho.mqtt.python.git
           cd paho.mqtt.c
           maje -j
           sudo make install
    
    - name: Install Mosquitto
      run : git clone https://github.com/eclipse/mosquitto
   
